proj_name: Kelly_AdultCDI_2020_16SrRNA
raw_fq: /mnt/isilon/zackular_lab_hpc/data/Kelly_AdultCDI_2020/FASTQ
manifest: /mnt/isilon/zackular_lab_hpc/data/Kelly_AdultCDI_2020/FASTQ/pe-33-manifest

# Fastq file suffix, following the read pair designation
suffix: .fastq.gz
# suffix: _1.fastq.gz

# Read pair designations
r1_suf: 1
r2_suf: 2
# r1_suf: R1
# r2_suf: R2

# QIIME2-specific flags
# Defaults for amplicon tag-sequencing - uncomment only parameters you need.

# ## 18S default (Stoeck et al. 2010 V4 primers)
# primerF: CCAGCASCYGCGGTAATTCC
# primerR: ACTTTCGTTCTTGATYRA
# primer_err: 0.4
# primer_overlap: 3
# # Merging reads for 18S:
# minoverlap: 10
# maxdiff: 4
# minlength: 270

# 16S default (Parada et al. modified EMP primers)
# primerF: GTGYCAGCMGCCGCGGTAA
# primerR: GGACTACNVGGGTWTCTAAT
## need to aks for V1-V2 primers
primerF: GTGYCAGCMGCCGCGGTAA
primerR: GGACTACNVGGGTWTCTAAT 
primer_err: 0.1
primer_overlap: 3
# Merging reads for 16S
minoverlap: 20
maxdiff: 4
minlength: 200

## Database
database: /vortexfs1/omics/huber/shu/db/pr2-db/V4-pr2_4.12.0.qza
database_classified: /vortexfs1/omics/huber/shu/db/pr2-db/V4-pr2_4.12.0-classifier.qza
database_tax: /vortexfs1/omics/huber/shu/db/pr2-db/pr2_4.12.0_tax.qza

## DADA2 - ASV flags
# truncation_len-f + truncation_len-r should > amplicon(V1-V2 ~350bp) + overlap (>20bp)
truncation_len-f: 220 # critical, need to determine from the QC report
truncation_len-r: 200 # reverse reads usually have lower quanlity at the end, and thus should truncate more
training: 1000000 #should be set higher for a non-test dataset
chimera: consensus

## diversity
sampling_depth: 10000
# Retained 6,170,000 (4.74%) features in 617 (92.64%) samples at the specifed sampling depth.
# https://forum.qiime2.org/t/how-to-select-a-sampling-depth/4265/13

## filter
min-frequency_all: 50
min-frequency_sample: 2000
min-samples: 2

## OTU clustering

# Quality filtering of merged reads
minphred: 4
qualwindow: 3 

# De novo OTU clustering
denovo_perc_id: 0.97
denovo_otu-thread: 1

# Chimera checking
chimera-thread: 1